# Prepara y estructura datos con Python I 🐍🖥️✍️

## Objetivos academicos

## Qué es python 🐍 y su uso en análisis de datos



Python 🐍 es un lenguaje de programación versátil, fácil de aprender y con una sintaxis cercana al lenguaje humano, ideal para quienes inician en análisis de datos. Su fuerza está en su ecosistema de librerías como **NumPy**, **pandas**, **Matplotlib** y **scikit-learn**, que permiten desde limpiar y transformar datos hasta crear visualizaciones y modelos de *machine learning*.

> Piensa en Python como una 🧰 navaja suiza: automatiza tareas, procesa grandes volúmenes de información y convierte datos en conocimiento para la toma de decisiones.

## Pensamiento analítico / pensamiento algorítmico 🧠💡


El **pensamiento analítico** consiste en descomponer un problema en partes más pequeñas para entenderlo y encontrar patrones. En análisis de datos, esto significa observar los datos desde distintas perspectivas, buscar relaciones y proponer hipótesis con base en evidencia.

Por otro lado, el **pensamiento algorítmico** se enfoca en cómo resolver esos problemas paso a paso, mediante instrucciones claras y ordenadas —como si explicaras a una computadora qué hacer. 🧩  

> En pocas palabras: el pensamiento analítico te ayuda a **entender el problema**, y el algorítmico a **diseñar la solución**. Juntos son la base para transformar datos en conocimiento accionable.

---

### 🔄 Flujo típico de análisis de datos en Python

1. **Definición del problema:** comprender qué pregunta queremos responder o qué decisión queremos apoyar.  
2. **Obtención de datos:** cargar la información desde archivos, bases de datos o APIs.  
3. **Limpieza y transformación:** tratar valores nulos, corregir errores y preparar los datos para el análisis.  
4. **Análisis exploratorio (EDA):** usar estadísticas y visualizaciones para descubrir patrones y tendencias.  
5. **Modelado:** aplicar técnicas estadísticas o de *machine learning* según el objetivo.  
6. **Interpretación y comunicación:** explicar resultados de forma clara y visual, con foco en la toma de decisiones.  

> Este flujo no siempre es lineal: los analistas suelen **volver a pasos anteriores** para mejorar la calidad del análisis y la comprensión del problema.

## Entorno de trabajo en Jupyter Notebook 💻✨


**Jupyter Notebook** es uno de los entornos más populares para trabajar con Python en análisis de datos. Combina en un mismo espacio **código ejecutable**, **texto explicativo**, **gráficos** y **resultados**, lo que lo convierte en una herramienta ideal para aprender, documentar y compartir proyectos de ciencia de datos.

Cada archivo de notebook tiene extensión `.ipynb` (*Interactive Python Notebook*) y está compuesto por **celdas**, que pueden ser de dos tipos principales:

- 🧮 **Celdas de código:** donde escribes y ejecutas instrucciones en Python.  
- 📝 **Celdas de markdown:** donde puedes incluir texto formateado, ecuaciones o imágenes para documentar tu proceso.  

El flujo de trabajo típico es iterativo: ejecutas código, observas resultados, haces ajustes y anotas tus hallazgos directamente en el mismo documento.  
> Piensa en Jupyter como tu **laboratorio interactivo** de análisis: un lugar donde los datos, el razonamiento y los resultados conviven en un solo espacio. 🔍📊

<center>
  <img src="https://www.silocreativo.com/wp-content/uploads/2019/05/markdown-cheatsheet.png" alt="Markdown Cheatsheet" style="max-width:50%; height:auto;" width="50%">
</center>

In [33]:
#Celda de código <- esto es un comentario

a= 2
b= "Hola"
c= 8
print(a)
print(a+c)

2
10

Seguir un estilo coherente al programar mejora la **legibilidad**, la **colaboración** y facilita el **mantenimiento del código**.  
Aquí algunas recomendaciones clave 👇  

- 🧩 **Nombrado de variables:** usa nombres descriptivos y en minúsculas, separados por guiones bajos.  
  Ejemplo: `edad_promedio`, `ventas_totales`, `openaq_pm25._clientes`.  
  > Evita nombres genéricos como `data` o `x` si no tienen un propósito claro.

- 💬 **Comentarios:** explica *por qué* haces algo, no solo *qué* hace el código.  
  Usa `#` para agregar comentarios breves o `""" ... """` para documentar funciones más largas.  

  ```python
  # Calculamos el promedio de ventas por región
  promedio = openaq_pm25.groupby("region")["ventas"].mean()
  ```

- ↔️ **Indentación:** usa **tabulaciones (Tab)** o **4 espacios** para mantener la estructura del código clara y evitar errores de sintaxis.  
  Todas las líneas dentro de un mismo bloque deben tener el mismo nivel de sangría.

  ```python
  for region in openaq_pm25["region"].unique():
      subset = openaq_pm25[openaq_pm25["region"] == region]
      print(region, subset["ventas"].mean())
  ```

> 🧠 Un código limpio no solo funciona bien, sino que también se entiende fácilmente. Escribe pensando en la persona que leerá tu código después (¡aunque seas tú mismo en el futuro!).

En Jupyter Notebook se recomienda **no abusar del uso de `print()`**, especialmente cuando el objetivo es solo visualizar resultados intermedios.  
Aprovecha el renderizado automático de Jupyter para mostrar **una sola salida por celda**, manteniendo el notebook limpio y legible.  
> ✨ Un notebook bien estructurado combina explicaciones en *markdown* y resultados claros, facilitando la lectura y el análisis paso a paso.

## Pandas para análisis de datos 🐼📊

**pandas** es la librería fundamental de Python para manipular, limpiar y analizar datos estructurados. Su nombre proviene de *Panel Data* y está construida sobre **NumPy**, lo que le da gran velocidad y flexibilidad para trabajar con grandes volúmenes de información.

---

### 📘 DataFrames
Un **DataFrame** es una tabla con filas y columnas, similar a una hoja de cálculo de Excel.

In [34]:
import pandas as pd

### 📂 Carga de datos en pandas (DataFrame)

In [35]:
# Cargar datos desde un archivo CSV
openaq_pm25=pd.read_csv('https://practicum-content.s3.us-west-1.amazonaws.com/datasets/openaq_pm25')

### 🔍 Exploración de datos

In [36]:
# Dimensiones del DataFrame
openaq_pm25.shape

(7240, 18)

In [37]:

# Nombres de columnas
openaq_pm25.columns

Index(['X', 'Y', 'OBJECTID', 'location_id', 'city', 'location', 'lastUpdated',
       'parameter', 'unit', 'value', 'value_2', 'unit_2', 'owner_name',
       'provider_name', 'instrument_name', 'url', 'country_name',
       'country_id'],
      dtype='object')

In [38]:

# Primeros, últimos registros y una muestra
openaq_pm25.head(),openaq_pm25.tail(),openaq_pm25.sample()

(             X            Y  OBJECTID  location_id    city location  \
 0 -11503014.36  2353020.757      2234        10536  Centro   Centro
 1 -11387519.15  2497577.408      6015       927942  Centro   Centro
 2 -11809390.03  3331455.745      8363      5638300  Centro   Centro
 3  14303300.11  4278336.641       108      2622664     호림동      호림동
 4  14331629.36  4276592.172       271      2623655     중방동      중방동

               lastUpdated parameter   unit   value  value_2  unit_2  \
 0  2021/10/01 15:00:00+00      pm25  µg/m³     NaN      NaN     NaN
 1  2021/09/24 11:00:00+00      pm25  µg/m³     NaN      NaN     NaN
 2  2021/10/01 14:00:00+00      pm25  µg/m³     NaN      NaN     NaN
 3  2021/10/01 15:00:00+00      pm25  µg/m³  9999.0      NaN     NaN
 4  2021/10/01 15:00:00+00      pm25  µg/m³  9999.0      NaN     NaN

                           owner_name                      provider_name  \
 0  Unknown Governmental Organization                     Sinaica Mexico
 1  Unknown Governmental Organization                     Sinaica Mexico
 2  Unknown Governmental Organization                     Sinaica Mexico
 3  Unknown Governmental Organization  Korea Air Ministry of Environment
 4  Unknown Governmental Organization  Korea Air Ministry of Environment

       instrument_name                                           url  \
 0  Government Monitor    https://explore.openaq.org/locations/10536
 1  Government Monitor   https://explore.openaq.org/locations/927942
 2  Government Monitor  https://explore.openaq.org/locations/5638300
 3  Government Monitor  https://explore.openaq.org/locations/2622664
 4  Government Monitor  https://explore.openaq.org/locations/2623655

         country_name country_id
 0             Mexico        MEX
 1             Mexico        MEX
 2             Mexico        MEX
 3  Republic of Korea        KOR
 4  Republic of Korea        KOR  ,
                 X            Y  OBJECTID  location_id              city  \
 7235 -4826211.996 -2617923.917      5657      5110472          Campinho
 7236 -4807499.189 -2620908.664      4991      5110511  Campo de Santana
 7237 -4805684.681 -2621500.844      5218      5636852               MAM
 7238 -4824620.127 -2615821.628      5219      5648811  Parque Madureira
 7239 -4824297.300 -2617223.124      4993      5110514         Madureira

               location             lastUpdated parameter   unit  value  \
 7235          Campinho  2021/10/01 15:00:00+00      pm25  µg/m³  13.49
 7236  Campo de Santana  2021/10/01 15:00:00+00      pm25  µg/m³  13.11
 7237               MAM  2021/10/01 15:00:00+00      pm25  µg/m³  12.53
 7238  Parque Madureira  2021/10/01 15:00:00+00      pm25  µg/m³  11.99
 7239         Madureira  2021/10/01 15:00:00+00      pm25  µg/m³  11.66

       value_2  unit_2                         owner_name  provider_name  \
 7235      NaN     NaN  Unknown Governmental Organization  Rio City Hall
 7236      NaN     NaN  Unknown Governmental Organization  Rio City Hall
 7237      NaN     NaN  Unknown Governmental Organization  Rio City Hall
 7238      NaN     NaN  Unknown Governmental Organization  Rio City Hall
 7239      NaN     NaN  Unknown Governmental Organization  Rio City Hall

          instrument_name                                           url  \
 7235  Government Monitor  https://explore.openaq.org/locations/5110472
 7236  Government Monitor  https://explore.openaq.org/locations/5110511
 7237  Government Monitor  https://explore.openaq.org/locations/5636852
 7238  Government Monitor  https://explore.openaq.org/locations/5648811
 7239  Government Monitor  https://explore.openaq.org/locations/5110514

      country_name country_id
 7235       Brazil        BRA
 7236       Brazil        BRA
 7237       Brazil        BRA
 7238       Brazil        BRA
 7239       Brazil        BRA  ,
                 X            Y  OBJECTID  location_id  \
 5305  2007871.437  8254348.806      7485      2163278

                             city                    location  \
 5305  Stockholm St Eriksgatan 83  Stockholm St Eriksgatan 83

                  lastUpdated parameter   unit   value  value_2  unit_2  \
 5305  2021/10/01 08:00:00+00      pm25  µg/m³  4.2237      NaN     NaN

                              owner_name provider_name     instrument_name  \
 5305  Unknown Governmental Organization           EEA  Government Monitor

                                                url country_name country_id
 5305  https://explore.openaq.org/locations/2163278       Sweden        SWE  )

In [39]:
openaq_pm25.head()

,X,Y,OBJECTID,location_id,city,location,lastUpdated,parameter,unit,value,value_2,unit_2,owner_name,provider_name,instrument_name,url,country_name,country_id
0,-11503014.36,2353020.757,2234,10536,Centro,Centro,2021/10/01 15:00:00+00,pm25,µg/m³,NaN,NaN,NaN,Unknown Governmental Organization,Sinaica Mexico,Government Monitor,https://explore.openaq.org/locations/10536,Mexico,MEX
1,-11387519.15,2497577.408,6015,927942,Centro,Centro,2021/09/24 11:00:00+00,pm25,µg/m³,NaN,NaN,NaN,Unknown Governmental Organization,Sinaica Mexico,Government Monitor,https://explore.openaq.org/locations/927942,Mexico,MEX
2,-11809390.03,3331455.745,8363,5638300,Centro,Centro,2021/10/01 14:00:00+00,pm25,µg/m³,NaN,NaN,NaN,Unknown Governmental Organization,Sinaica Mexico,Government Monitor,https://explore.openaq.org/locations/5638300,Mexico,MEX
3,14303300.11,4278336.641,108,2622664,호림동,호림동,2021/10/01 15:00:00+00,pm25,µg/m³,9999.0,NaN,NaN,Unknown Governmental Organization,Korea Air Ministry of Environment,Government Monitor,https://explore.openaq.org/locations/2622664,Republic of Korea,KOR
4,14331629.36,4276592.172,271,2623655,중방동,중방동,2021/10/01 15:00:00+00,pm25,µg/m³,9999.0,NaN,NaN,Unknown Governmental Organization,Korea Air Ministry of Environment,Government Monitor,https://explore.openaq.org/locations/2623655,Republic of Korea,KOR

In [40]:
print(openaq_pm25.head())

             X            Y  OBJECTID  location_id    city location  \
0 -11503014.36  2353020.757      2234        10536  Centro   Centro
1 -11387519.15  2497577.408      6015       927942  Centro   Centro
2 -11809390.03  3331455.745      8363      5638300  Centro   Centro
3  14303300.11  4278336.641       108      2622664     호림동      호림동
4  14331629.36  4276592.172       271      2623655     중방동      중방동

              lastUpdated parameter   unit   value  value_2  unit_2  \
0  2021/10/01 15:00:00+00      pm25  µg/m³     NaN      NaN     NaN
1  2021/09/24 11:00:00+00      pm25  µg/m³     NaN      NaN     NaN
2  2021/10/01 14:00:00+00      pm25  µg/m³     NaN      NaN     NaN
3  2021/10/01 15:00:00+00      pm25  µg/m³  9999.0      NaN     NaN
4  2021/10/01 15:00:00+00      pm25  µg/m³  9999.0      NaN     NaN

                          owner_name                      provider_name  \
0  Unknown Governmental Organization                     Sinaica Mexico
1  Unknown Governmental Organization                     Sinaica Mexico
2  Unknown Governmental Organization                     Sinaica Mexico
3  Unknown Governmental Organization  Korea Air Ministry of Environment
4  Unknown Governmental Organization  Korea Air Ministry of Environment

      instrument_name                                           url  \
0  Government Monitor    https://explore.openaq.org/locations/10536
1  Government Monitor   https://explore.openaq.org/locations/927942
2  Government Monitor  https://explore.openaq.org/locations/5638300
3  Government Monitor  https://explore.openaq.org/locations/2622664
4  Government Monitor  https://explore.openaq.org/locations/2623655

        country_name country_id
0             Mexico        MEX
1             Mexico        MEX
2             Mexico        MEX
3  Republic of Korea        KOR
4  Republic of Korea        KOR


En **Jupyter Notebook**, cuando escribes una expresión en la **última línea** de una celda (por ejemplo, `openaq_pm25.head()`), el resultado **se muestra automáticamente** con un formato visual atractivo.  
Esto ocurre porque Jupyter interpreta el valor devuelto por la última instrucción y lo renderiza de manera enriquecida (tablas, gráficos, HTML, etc.).  

```python
# Muestra una vista previa del DataFrame con formato visual
openaq_pm25.head()
```

En cambio, si usas **`print()`**, el contenido se muestra como texto plano en la consola, sin formato visual ni estilos adicionales:  

```python
# Muestra el mismo resultado pero sin formato tabular
print(openaq_pm25.head())
```

> 💡 Usa `print()` cuando necesites mostrar múltiples salidas dentro de la misma celda o cuando quieras controlar el formato del texto; pero si solo te interesa ver el resultado, basta con escribir la expresión en la última línea.

In [41]:
# Información general del DataFrame
openaq_pm25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7240 entries, 0 to 7239
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   X                7240 non-null   float64
 1   Y                7240 non-null   float64
 2   OBJECTID         7240 non-null   int64
 3   location_id      7240 non-null   int64
 4   city             7237 non-null   object
 5   location         7237 non-null   object
 6   lastUpdated      7231 non-null   object
 7   parameter        7240 non-null   object
 8   unit             7240 non-null   object
 9   value            7225 non-null   float64
 10  value_2          0 non-null      float64
 11  unit_2           0 non-null      float64
 12  owner_name       7240 non-null   object
 13  provider_name    7236 non-null   object
 14  instrument_name  7017 non-null   object
 15  url              7240 non-null   object
 16  country_name     7240 non-null   object
 17  country_id       7079 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 1018.3+ KB

En un DataFrame, cada columna tiene un **tipo de dato** (*dtype*) que determina cómo se almacenan y procesan los valores.  
Los más comunes son:

- **int64:** números enteros (por ejemplo, 1, 25, 100).  
- **float64:** números decimales (por ejemplo, 3.14, 250.5).  
- **object:** texto o datos mixtos (strings).  
- **bool:** valores lógicos `True` o `False`.  
- **datetime64:** fechas y tiempos (`YYYY-MM-DD HH:MM:SS`).  
- **category:** variables con categorías fijas, útiles para optimizar memoria.

> 📊 Puedes consultar los tipos de datos de tu DataFrame con `openaq_pm25.dtypes` o convertirlos con `openaq_pm25.astype()`.

### 📊 Exploración de estadísticas

In [42]:
# Calcular estadísticas básicas include='all'
openaq_pm25.describe()

,X,Y,OBJECTID,location_id,value,value_2,unit_2
count,7.240000e+03,7.240000e+03,7240.000000,7.240000e+03,7225.000000,0.0,0.0
mean,8.591821e+05,4.377114e+06,4350.401657,2.069706e+06,57.770281,NaN,NaN
std,1.022286e+07,2.200803e+06,2829.029420,1.784755e+06,617.010918,NaN,NaN
min,-1.757238e+07,-5.983764e+06,1.000000,2.600000e+01,0.000000,NaN,NaN
25%,-9.323457e+06,3.881920e+06,1823.750000,1.078225e+04,4.000000,NaN,NaN
50%,9.252275e+05,4.524451e+06,4088.500000,2.162598e+06,8.000000,NaN,NaN
75%,1.119160e+07,5.697842e+06,6858.500000,3.316741e+06,14.400000,NaN,NaN
max,1.951659e+07,9.962817e+06,9514.000000,5.975180e+06,9999.000000,NaN,NaN

### 🧩 Manejando datos

**Renombrar columnas**

In [45]:
openaq_pm25.rename(columns={"value": "pm25_level"})

,X,Y,OBJECTID,location_id,city,location,lastUpdated,parameter,unit,pm25_level,value_2,unit_2,owner_name,provider_name,instrument_name,url,country_name,country_id
0,-1.150301e+07,2353020.757,2234,10536,Centro,Centro,2021/10/01 15:00:00+00,pm25,µg/m³,NaN,NaN,NaN,Unknown Governmental Organization,Sinaica Mexico,Government Monitor,https://explore.openaq.org/locations/10536,Mexico,MEX
1,-1.138752e+07,2497577.408,6015,927942,Centro,Centro,2021/09/24 11:00:00+00,pm25,µg/m³,NaN,NaN,NaN,Unknown Governmental Organization,Sinaica Mexico,Government Monitor,https://explore.openaq.org/locations/927942,Mexico,MEX
2,-1.180939e+07,3331455.745,8363,5638300,Centro,Centro,2021/10/01 14:00:00+00,pm25,µg/m³,NaN,NaN,NaN,Unknown Governmental Organization,Sinaica Mexico,Government Monitor,https://explore.openaq.org/locations/5638300,Mexico,MEX
3,1.430330e+07,4278336.641,108,2622664,호림동,호림동,2021/10/01 15:00:00+00,pm25,µg/m³,9999.00,NaN,NaN,Unknown Governmental Organization,Korea Air Ministry of Environment,Government Monitor,https://explore.openaq.org/locations/2622664,Republic of Korea,KOR
4,1.433163e+07,4276592.172,271,2623655,중방동,중방동,2021/10/01 15:00:00+00,pm25,µg/m³,9999.00,NaN,NaN,Unknown Governmental Organization,Korea Air Ministry of Environment,Government Monitor,https://explore.openaq.org/locations/2623655,Republic of Korea,KOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,-4.826212e+06,-2617923.917,5657,5110472,Campinho,Campinho,2021/10/01 15:00:00+00,pm25,µg/m³,13.49,NaN,NaN,Unknown Governmental Organization,Rio City Hall,Government Monitor,https://explore.openaq.org/locations/5110472,Brazil,BRA
7236,-4.807499e+06,-2620908.664,4991,5110511,Campo de Santana,Campo de Santana,2021/10/01 15:00:00+00,pm25,µg/m³,13.11,NaN,NaN,Unknown Governmental Organization,Rio City Hall,Government Monitor,https://explore.openaq.org/locations/5110511,Brazil,BRA
7237,-4.805685e+06,-2621500.844,5218,5636852,MAM,MAM,2021/10/01 15:00:00+00,pm25,µg/m³,12.53,NaN,NaN,Unknown Governmental Organization,Rio City Hall,Government Monitor,https://explore.openaq.org/locations/5636852,Brazil,BRA
7238,-4.824620e+06,-2615821.628,5219,5648811,Parque Madureira,Parque Madureira,2021/10/01 15:00:00+00,pm25,µg/m³,11.99,NaN,NaN,Unknown Governmental Organization,Rio City Hall,Government Monitor,https://explore.openaq.org/locations/5648811,Brazil,BRA
7239,-4.824297e+06,-2617223.124,4993,5110514,Madureira,Madureira,2021/10/01 15:00:00+00,pm25,µg/m³,11.66,NaN,NaN,Unknown Governmental Organization,Rio City Hall,Government Monitor,https://explore.openaq.org/locations/5110514,Brazil,BRA

El parámetro **`inplace=True`** indica que la operación debe aplicarse **directamente sobre el DataFrame original**, sin necesidad de reasignarlo a una nueva variable.  
Por ejemplo, al ejecutar `openaq_pm25.dropna(inplace=True)`, las filas con valores nulos se eliminan del propio `openaq_pm25.`.  
Si en cambio usamos `inplace=False` (valor por defecto), la función devuelve una **copia modificada** del DataFrame, dejando el original sin cambios.  
> 💡 Úsalo con cuidado: `inplace=True` ahorra memoria, pero puede dificultar deshacer cambios si necesitas conservar la versión anterior del DataFrame.

In [46]:
openaq_pm25.rename(columns={"value": "pm25_level"},inplace=True)

**Reordenar o seleccionar columnas**

In [47]:
openaq_pm25_selection=openaq_pm25[['country_id', 'pm25_level', 'unit']]
openaq_pm25_selection

     country_id  pm25_level   unit
0           MEX         NaN  µg/m³
1           MEX         NaN  µg/m³
2           MEX         NaN  µg/m³
3           KOR     9999.00  µg/m³
4           KOR     9999.00  µg/m³
...         ...         ...    ...
7235        BRA       13.49  µg/m³
7236        BRA       13.11  µg/m³
7237        BRA       12.53  µg/m³
7238        BRA       11.99  µg/m³
7239        BRA       11.66  µg/m³

[7240 rows x 3 columns]

**Eliminar columnas**

In [48]:
openaq_pm25.drop(columns=["sexo"], inplace=True) 
openaq_pm25.head()

KeyError: "['sexo'] not found in axis"

### 🧼 Limpieza y transformación de datos

**Manejo de valores nulos/faltantes**

In [ ]:
# Eliminar filas con valores nulos
openaq_pm25.dropna(inplace=True)

In [ ]:
# Reemplazar valores nulos con la media
openaq_pm25["diagnóstico_confirmado"].fillna('descononocido', inplace=True)

**Manejo de duplicados**

In [ ]:
# Detectar duplicados
openaq_pm25.duplicated().sum()

# Eliminar duplicados
openaq_pm25.drop_duplicates(inplace=True)

**Formatear datos**

In [ ]:
# Convertir texto a minúsculas
openaq_pm25["sintoma_principal"] = openaq_pm25["sintoma_principal"].str.lower()

# Cambiar tipo de dato
openaq_pm25["edad"] = openaq_pm25["edad"].astype(float)

### 🔎 Filtrar, ordenar y resumir datos

**Filtrar datos en pandas**

In [ ]:
# Filtrar pacientes con mas de 40 años
openaq_pm25._filtrado = openaq_pm25[openaq_pm25["edad"] > 40]
openaq_pm25._filtrado

**Ordenar datos**

In [ ]:
# Ordenar de mayor a menor
openaq_pm25.sort_values(by="region", ascending=False)

### 🔗 Combinar y estructurar datasets

**Combinar DataFrames (merge)**

In [ ]:
clientes = pd.DataFrame({
    "cliente": ["ana", "luis", "maría", "carlos"],
    "ciudad": ["CDMX", "Monterrey", "Guadalajara", "Puebla"]
})

ventas = pd.DataFrame({
    "cliente": ["ana", "luis", "maría", "carlos"],
    "monto_ventas": [250, 400, 150, 300]
})

openaq_pm25._combinado = pd.merge(clientes, ventas, on="cliente")
openaq_pm25._combinado

**Ordenar datasets**

In [ ]:
# Ordenar alfabéticamente por cliente
openaq_pm25._combinado.sort_values(by="cliente", inplace=True)
openaq_pm25._combinado

> 🐼 **En resumen:** pandas te permite explorar, limpiar, transformar y combinar datos de forma rápida y sencilla, convirtiéndose en una herramienta esencial en cualquier flujo de análisis de datos.

## 🚀 Para seguir aprendiendo :

---

- 📚 Vuelve a revisar este notebook y trata resolver por tu cuenta  nuevamente
- 💬 Recuerda que en Discord puedes dejar todos tus comentarios y dudas sobre el contenido del sprint en [`Discord`](https://discord.com/channels/1081207584104656986/1420849538196836472).
    - 📝 Si tienes preguntas sobre tu proyecto, usa el canal [`#project`](https://discord.com/channels/1081207584104656986/1420848813186351134) para recibir ayuda y compartir ideas.
    - 🤝 Aprovecha el espacio de `CoLearning` para aclarar tus dudas junto con otros estudiantes e instructores: [Co-Learning](https://discord.com/channels/1081207584104656986/1197953851391746119).
    - En tus preguntas recuerda etiquetar a `@Dataconsulta` y ubica tu pregunta de acuerdo a `Sprint/Capitulo/Seccion`
- 📅 ¿Necesitas ayuda personalizada? Puedes agendar una sesión `1:1` conmigo aquí: [1:1 Roman Castillo](https://scheduler.zoom.us/roman-castillo/1-1-roman-castillo).

- Por último hazme paro y responde la encuesta al final de la sesión, me sirve para poder ayudarte mejor 

¡Sigue practicando y no dudes en pedir apoyo cuando lo necesites! 💪✨