# Técnicas para mineria de datos

---

**Objetivos académicos**

1. Comprender los conceptos básicos de la minería de datos web y su importancia para obtener información de páginas y APIs.
2. Identificar la estructura y los elementos principales del HTML para facilitar la extracción de datos relevantes.
3. Aplicar técnicas de web scraping utilizando Python, `requests` y `BeautifulSoup` para recolectar y procesar información desde sitios web.
4. Utilizar expresiones regulares y manipulación de datos para filtrar, limpiar y organizar la información extraída.
5. Interactuar con APIs REST, comprendiendo los métodos HTTP más comunes y el manejo de datos en formato JSON, así como su integración en DataFrames para análisis posterior.

---

## Mineria de datos

**🔎 Introducción a la minería web**  

---

¿Sabías que puedes extraer información directamente desde cualquier página web? 🌐 La minería web es una técnica súper útil que permite a analistas y desarrolladores obtener datos valiosos de sitios en línea, especialmente cuando no se cuenta con suficiente información para hacer un buen análisis. A través de este proceso, podemos complementar nuestros datos, descubrir patrones interesantes y hasta encontrar cosas que no esperábamos 🎯. Para hacerlo, es clave entender cómo funciona el HTML, el lenguaje que da estructura a todas las páginas web. Cada título, párrafo, tabla o imagen está organizada con etiquetas especiales, ¡y conocerlas nos abre la puerta a todo ese contenido! 🚪📄

**📬 Peticiones HTTP y cómo obtener datos**  

---

Cuando visitas una página web, tu navegador le manda una "petición" al servidor usando un protocolo llamado HTTP. A cambio, el servidor responde con el código HTML de la página 🧾. Lo mejor es que podemos imitar ese proceso desde Python usando la librería `requests` 🐍. Al hacerlo, recibimos el contenido de la página en forma de texto, que luego podemos analizar y filtrar para obtener solo lo que nos interesa: nombres de productos, precios, tablas de datos... lo que sea 📊🛒. Con herramientas como `BeautifulSoup`, ese texto se convierte en una fuente de información muy poderosa. ¡Es como tener una lupa para explorar la web! 🔍

**📬 Códigos de respuesta HTTP comunes**

---

Cuando haces una solicitud a una API (o a cualquier servidor web), recibes una respuesta con un código que indica si todo salió bien o si hubo algún problema. Aquí están los más comunes:

| Código | Significado             | Descripción breve                                  |
|--------|-------------------------|----------------------------------------------------|
| 200    | OK                      | La solicitud fue exitosa y se devolvieron los datos. |
| 201    | Created                 | El recurso fue creado exitosamente.               |
| 204    | No Content              | La solicitud fue exitosa, pero no hay datos que devolver. |
| 301    | Moved Permanently       | La URL solicitada se ha movido permanentemente.   |
| 302    | Found                   | El recurso está temporalmente en otra ubicación.  |
| 400    | Bad Request             | La solicitud tiene un error de sintaxis.          |
| 401    | Unauthorized            | Falta autenticación o es inválida.                |
| 403    | Forbidden               | Tienes prohibido el acceso al recurso.            |
| 404    | Not Found               | El recurso solicitado no existe.                  |
| 500    | Internal Server Error   | Error inesperado en el servidor.                  |
| 502    | Bad Gateway             | El servidor recibió una respuesta inválida.       |
| 503    | Service Unavailable     | El servidor está sobrecargado o en mantenimiento. |

## 🏗️ Estructura básica de una página HTML

Una página web está construida con HTML (HyperText Markup Language), que es el lenguaje que le da estructura y formato a todo lo que ves en Internet. El HTML organiza el contenido usando **etiquetas** (tags), que indican el propósito de cada elemento: títulos, párrafos, imágenes, tablas, enlaces, etc.  
Las etiquetas pueden tener **atributos** que añaden información extra, como identificadores (`id`), clases (`class`), enlaces (`href`), rutas de imágenes (`src`), entre otros.  
La estructura básica de cualquier página HTML suele verse así:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Título de la página</title>
  </head>
  <body>
    <h1 id="principal" class="titulo">Encabezado principal</h1>
    <p class="intro">Este es un párrafo de texto.</p>
    <a href="https://tripleten.com" target="_blank" class="enlace-destacado">Un enlace</a>
    <img src="https://images.squarespace-cdn.com/content/v1/5d1ea2be4d6d79000127d718/e5ed5590-89f1-44ce-a0c0-207d87b0273c/tripleten-que-es-como-funciona-cuanto-cuesta.png" alt="Descripción de la imagen" class="img-responsive">
    <table class="tabla-datos">
      <tr><th>Columna 1</th><th>Columna 2</th></tr>
      <tr><td data-info="dato1">Dato 1</td><td>Dato 2</td></tr>
    </table>
  </body>
</html>
```

En este ejemplo, puedes ver atributos como `id`, `class`, `href`, `src`, `alt`, `target` y `data-info`, que ayudan a identificar, clasificar o describir los elementos de la página.

---



## 🔖 Etiquetas para la extracción de datos

Al hacer minería web o scraping, hay ciertas etiquetas HTML que resultan especialmente útiles para extraer información relevante:

- `<h1>`, `<h2>`, `<h3>`...: Encabezados o títulos de secciones.
- `<p>`: Párrafos de texto.
- `<a>`: Enlaces a otras páginas o recursos (el atributo `href` contiene la URL).
- `<img>`: Imágenes (el atributo `src` contiene la ruta de la imagen).
- `<table>`, `<tr>`, `<td>`, `<th>`: Tablas y sus celdas, ideales para datos estructurados.
- `<ul>`, `<ol>`, `<li>`: Listas no ordenadas y ordenadas.
- `<div>`, `<span>`: Contenedores genéricos, útiles para agrupar y dar formato a otros elementos.

Conocer estas etiquetas te permitirá identificar y extraer la información que necesitas de cualquier página web de manera eficiente y precisa. 🕵️‍♂️📄

## 🧪 Ejercicios de práctica: Web scraping con Python 🐍

Trabajaremos con el sitio [http://books.toscrape.com/](http://books.toscrape.com/), una página que simula una tienda de libros. El objetivo será obtener información útil desde el código HTML usando `requests`, `BeautifulSoup` y expresiones regulares.

---

In [1]:
import re
import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd

### 🧵 Ejercicio 1: Obtener el código HTML  
**Objetivo:** Hacer una solicitud HTTP y visualizar el código fuente de la página.

In [2]:

url = "http://books.toscrape.com/"
res = requests.get(url)

print(res.status_code)  # Debería imprimir 200
print(res.text[:1000])  # Imprime los primeros 1000 caracteres del HTML

200
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:29" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="static/oscar/favicon.

In [3]:
with open('html_content.txt','w') as f:
  f.write(res.text)

### 🔖 Ejercicio 2: Buscar todos los títulos de los libros en la portada  
**Objetivo:** Usar `BeautifulSoup` para extraer los títulos de todos los libros listados en la página de inicio.

---

In [4]:

soup = BeautifulSoup(res.text, "lxml")
books = soup.find_all("h3")

for book in books:
    print(book.find("a")["title"])
    #print(book.text)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

### 🎯 Ejercicio 3: Buscar libros con 5 estrellas  
**Objetivo:** Filtrar elementos usando atributos de clase para identificar libros con calificación de 5 estrellas.

In [5]:
five_star_books = soup.find_all("p", class_="star-rating Five")

for tag in five_star_books:
    title = tag.find_next("h3").find("a")["title"]
    print(f"🌟 {title}")

🌟 Sapiens: A Brief History of Humankind
🌟 Set Me Free
🌟 Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
🌟 Rip it Up and Start Again

### 💰 Ejercicio 4: Extraer precios usando expresiones regulares  
**Objetivo:** Usar `re` para filtrar todos los precios que aparecen en el HTML.

Las **expresiones regulares** son herramientas muy útiles en programación que permiten buscar, identificar y extraer patrones específicos dentro de textos. Por ejemplo, puedes usarlas para encontrar precios, correos electrónicos o palabras clave dentro del código HTML de una página web. En el web scraping, las expresiones regulares ayudan a filtrar y limpiar la información obtenida, facilitando el análisis de los datos.

| Carácter/Patrón | Explicación                                      | Ejemplo de uso                  |
|-----------------|--------------------------------------------------|---------------------------------|
| .               | Cualquier carácter excepto salto de línea         | `a.b` encuentra "acb", "a9b"    |
| ^               | Inicio de línea                                  | `^Hola` encuentra "Hola mundo"  |
| $               | Fin de línea                                     | `mundo$` encuentra "Hola mundo" |
| *               | Cero o más repeticiones                          | `ab*c` encuentra "ac", "abc", "abbc" |
| +               | Una o más repeticiones                           | `ab+c` encuentra "abc", "abbc"  |
| ?               | Cero o una repetición (opcional)                 | `colou?r` encuentra "color", "colour" |
| []              | Conjunto de caracteres                           | `[aeiou]` encuentra cualquier vocal |
| [^]             | Cualquier carácter excepto los indicados          | `[^0-9]` encuentra no dígitos   |
| {n}             | Exactamente n repeticiones                       | `a{3}` encuentra "aaa"          |
| {n,}            | Al menos n repeticiones                          | `a{2,}` encuentra "aa", "aaa"   |
| {n,m}           | Entre n y m repeticiones                         | `a{2,4}` encuentra "aa", "aaa", "aaaa" |
| \d              | Cualquier dígito (equivale a [0-9])              | `\d+` encuentra "123" en "abc123" |
| \D              | Cualquier no dígito                              | `\D+` encuentra "abc" en "abc123" |
| \w              | Cualquier carácter alfanumérico o guion bajo     | `\w+` encuentra "abc123"        |
| \W              | Cualquier carácter no alfanumérico               | `\W+` encuentra "!" en "abc!"   |
| \s              | Cualquier espacio en blanco                      | `\s+` encuentra espacios, tabulaciones |
| \S              | Cualquier carácter que no sea espacio en blanco  | `\S+` encuentra "Hola" en "Hola mundo" |
| \               | Carácter de escape para símbolos especiales      | `\.` encuentra el punto "."     |
| ( )             | Agrupación y captura                             | `(abc)+` encuentra "abcabc"     |
| \|              | Alternancia (o lógico)                           | `perro\|gato` encuentra "perro" o "gato" |

In [6]:

prices = re.findall(r"£\d+\.\d{2}", res.text)
print(prices)

['£51.77', '£53.74', '£50.10', '£47.82', '£54.23', '£22.65', '£33.34', '£17.93', '£22.60', '£52.15', '£13.99', '£20.66', '£17.46', '£52.29', '£35.02', '£57.25', '£23.88', '£37.59', '£51.33', '£45.17']

### 📦 Ejercicio 5: Combina título y precio  
**Objetivo:** Crear un pequeño script que imprima título y precio de cada libro.

In [7]:
books = soup.find_all("article", class_="product_pod")

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    print(f"{title} - {price}")

A Light in the Attic - Â£51.77
Tipping the Velvet - Â£53.74
Soumission - Â£50.10
Sharp Objects - Â£47.82
Sapiens: A Brief History of Humankind - Â£54.23
The Requiem Red - Â£22.65
The Dirty Little Secrets of Getting Your Dream Job - Â£33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull - Â£17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics - Â£22.60
The Black Maria - Â£52.15
Starving Hearts (Triangular Trade Trilogy, #1) - Â£13.99
Shakespeare's Sonnets - Â£20.66
Set Me Free - Â£17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) - Â£52.29
Rip it Up and Start Again - Â£35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 - Â£57.25
Olio - Â£23.88
Mesaerion: The Best Science Fiction Stories 1800-1849 - Â£37.59
Libertarianism for Beginners - Â£51.33
It's Only the Himalayas - Â£45.17

### 📂 Ejercicio 6: Obtener enlaces a detalles de cada libro  
**Objetivo:** Extraer el atributo `href` de cada libro para obtener su URL individual.

In [8]:
base_url = "http://books.toscrape.com/"
for book in books:
    relative_link = book.h3.a["href"]
    print(base_url + relative_link.replace('../', '').strip())

http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
http://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
http://books.toscrape.com/catalogue/soumission_998/index.html
http://books.toscrape.com/catalogue/sharp-objects_997/index.html
http://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
http://books.toscrape.com/catalogue/the-requiem-red_995/index.html
http://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
http://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
http://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
http://books.toscrape.com/catalogue/the-black-maria_991/index.html
http://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
http://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
http://books.toscrape.com/catalogue/set-me-free_988/index.html
http://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
http://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
http://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
http://books.toscrape.com/catalogue/olio_984/index.html
http://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
http://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html

### 🧹 Ejercicio 7: Filtrar libros con título que contenga una palabra clave  
**Objetivo:** Usar regex para encontrar libros que contengan, por ejemplo, la palabra "Secret".

In [9]:
pattern = re.compile(r"secret", re.IGNORECASE)

for book in books:
    title = book.h3.a["title"]
    if pattern.search(title):
        print(f"📘 {title}")

📘 The Dirty Little Secrets of Getting Your Dream Job

### 🔢 Ejercicio 8: Contar cuántos libros tienen 3, 4 o 5 estrellas  
**Objetivo:** Contar y clasificar libros según la cantidad de estrellas.

In [10]:
ratings = ["Three", "Four", "Five"]
for rating in ratings:
    count = len(soup.find_all("p", class_="star-rating " + rating))
    print(f"⭐ {rating} stars: {count} libros")

⭐ Three stars: 3 libros
⭐ Four stars: 4 libros
⭐ Five stars: 4 libros

### 📝 Ejercicio 9: Guardar los títulos y precios en un archivo CSV  
**Objetivo:** Practicar exportación de datos.

In [11]:
with open("libros.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Título", "Precio"])
    for book in books:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        writer.writerow([title, price])

### 🧮 Ejercicio 10: Convertir los datos en un DataFrame  
**Objetivo:** Crear un `DataFrame` con columnas para título, precio y calificación.

In [12]:
data = []
for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    price =  re.sub(r'[^0-9.]', '', price)
    rating_class = book.find("p")["class"]
    rating = rating_class[1] if len(rating_class) > 1 else "No rating"
    data.append({"Título": title, "Precio": price, "Estrellas": rating})

df = pd.DataFrame(data)
df

                                               Título Precio Estrellas
0                                A Light in the Attic  51.77     Three
1                                  Tipping the Velvet  53.74       One
2                                          Soumission  50.10       One
3                                       Sharp Objects  47.82      Four
4               Sapiens: A Brief History of Humankind  54.23      Five
5                                     The Requiem Red  22.65       One
6   The Dirty Little Secrets of Getting Your Dream...  33.34      Four
7   The Coming Woman: A Novel Based on the Life of...  17.93     Three
8   The Boys in the Boat: Nine Americans and Their...  22.60      Four
9                                     The Black Maria  52.15       One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       Two
11                              Shakespeare's Sonnets  20.66      Four
12                                        Set Me Free  17.46      Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29      Five
14                          Rip it Up and Start Again  35.02      Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25     Three
16                                               Olio  23.88       One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       One
18                       Libertarianism for Beginners  51.33       Two
19                            It's Only the Himalayas  45.17       Two


### 📊 Ejercicio 10: Calcular el precio promedio de los libros de la portada  
**Objetivo:** Convertir los precios a float y calcular el promedio.

In [13]:
df['Precio'] = pd.to_numeric(df['Precio'], errors='coerce')
(
    df.groupby('Estrellas')['Precio'].mean()
)

Estrellas
Five     39.750000
Four     31.105000
One      40.018333
Three    42.316667
Two      36.830000
Name: Precio, dtype: float64

# API's

**🔗 ¿Qué es una API?**  
Una API (Interfaz de Programación de Aplicaciones) es un conjunto de reglas que permite que dos programas se comuniquen entre sí. En el contexto del análisis de datos, las APIs permiten acceder a información alojada en servidores externos de forma estructurada, rápida y segura, sin tener que extraer datos directamente desde el HTML de una página web. Usar una API es como hacer una solicitud en un restaurante: tú pides (por ejemplo, el clima de hoy) y el servidor te responde con exactamente lo que necesitas, en un formato limpio como JSON o XML.

---

**📋 Tipos de llamadas HTTP comunes en una API**

| Método | Descripción | Uso común |
|--------|-------------|-----------|
| `GET`    | Solicita datos desde el servidor | Obtener información (lectura) |
| `POST`   | Envía datos al servidor | Crear un nuevo recurso |
| `PUT`    | Reemplaza un recurso existente | Actualizar por completo un dato |
| `PATCH`  | Modifica parcialmente un recurso | Editar parte de la información |
| `DELETE` | Elimina un recurso | Borrar datos del servidor |

**🗂️ ¿Qué es el formato JSON y por qué es tan usado en APIs?**  
JSON (JavaScript Object Notation) es un formato ligero y estructurado para intercambiar datos. Se basa en pares clave-valor, muy parecido a los diccionarios en Python o los objetos en JavaScript. Su sintaxis sencilla lo hace fácil de leer para los humanos y muy eficiente para las máquinas. 🌍

JSON se ha convertido en el formato preferido para las respuestas de muchas APIs porque permite transmitir información de forma clara, compacta y estandarizada. Cuando haces una llamada a una API, por ejemplo para obtener datos del clima o los detalles de un producto, el servidor suele responder con un objeto JSON. Esto facilita el procesamiento de los datos en aplicaciones web, móviles o scripts de análisis. Su amplia compatibilidad con casi todos los lenguajes de programación modernos ha hecho que JSON sea adoptado de manera masiva en el desarrollo de software y análisis de datos. 🔄📡

## 🧪 Práctica con JSONPlaceholder API (GET y POST)

Trabajaremos con la API pública [https://jsonplaceholder.typicode.com](https://jsonplaceholder.typicode.com), que simula el comportamiento de una API REST real. Los recursos disponibles incluyen `posts`, `comments`, `users`, entre otros.

### 🔍 Ejercicio 1: Obtener todas las publicaciones
**Objetivo:** Usar `requests.get()` para obtener una lista de publicaciones.

In [14]:

url = "https://jsonplaceholder.typicode.com/posts"
res = requests.get(url)

print(res.status_code)
print(res.json()[:3])  # Muestra las primeras 3 publicaciones

200
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

### 💬 Ejercicio 3: Obtener todos los comentarios de una publicación  
**Objetivo:** Usar parámetros en la URL para filtrar comentarios.

In [15]:
params = {"postId": 1}
res = requests.get("https://jsonplaceholder.typicode.com/comments", params=params)

for comment in res.json():
    print(comment["email"], "-", comment["body"][:40], "...")

Eliseo@gardner.biz - laudantium enim quasi est quidem magnam  ...
Jayne_Kuhic@sydney.com - est natus enim nihil est dolore omnis vo ...
Nikita@garfield.biz - quia molestiae reprehenderit quasi asper ...
Lew@alysha.tv - non et atque
occaecati deserunt quas acc ...
Hayden@althea.biz - harum non quasi et ratione
tempore iure  ...

### 📝 Ejercicio 4: Crear una nueva publicación (POST)  
**Objetivo:** Simular la creación de un post usando `requests.post()`.

In [16]:
payload = {
    "title": "Mi primer post",
    "body": "Este es un post de prueba para la clase.",
    "userId": 1
}

res = requests.post("https://jsonplaceholder.typicode.com/posts", json=payload)
print(res.status_code)
print(res.json())

201
{'title': 'Mi primer post', 'body': 'Este es un post de prueba para la clase.', 'userId': 1, 'id': 101}

### 🧪 Ejercicio 5: Crear un comentario en una publicación  
**Objetivo:** Simular un comentario nuevo con `POST`.

In [17]:
payload = {
    "postId": 1,
    "name": "Comentario de prueba",
    "email": "ejemplo@email.com",
    "body": "¡Este es un comentario para practicar!"
}

res = requests.post("https://jsonplaceholder.typicode.com/comments", json=payload)
print(res.json())

{'postId': 1, 'name': 'Comentario de prueba', 'email': 'ejemplo@email.com', 'body': '¡Este es un comentario para practicar!', 'id': 501}

### 🗃️ Ejercicio 6: Extraer publicaciones y convertirlas a DataFrame  
**Objetivo:** Obtener publicaciones de un usuario y convertirlas en un DataFrame.

In [18]:

params = {"userId": 2}
res = requests.get("https://jsonplaceholder.typicode.com/posts", params=params)
posts = res.json()

df = pd.DataFrame(posts)
df.head()

,userId,id,title,body
0,2,11,et ea vero quia laudantium autem,delectus reiciendis molestiae occaecati non mi...
1,2,12,in quibusdam tempore odit est dolorem,itaque id aut magnam\npraesentium quia et ea o...
2,2,13,dolorum ut in voluptas mollitia et saepe quo a...,aut dicta possimus sint mollitia voluptas comm...
3,2,14,voluptatem eligendi optio,fuga et accusamus dolorum perferendis illo vol...
4,2,15,eveniet quod temporibus,reprehenderit quos placeat\nvelit minima offic...

## En resumen en esta sesion revisamos:


1. **Introducción a la minería de datos web:**  
   Aprendiste qué es la minería de datos web, su importancia y cómo puede ayudarte a obtener información valiosa de páginas y APIs.

2. **Estructura y etiquetas HTML:**  
   Identificaste los elementos principales del HTML (como `<h1>`, `<p>`, `<a>`, `<table>`, etc.) que facilitan la extracción de datos relevantes en el web scraping.

3. **Web scraping con Python:**  
   Practicaste cómo usar `requests` y `BeautifulSoup` para recolectar, filtrar y organizar información desde sitios web, incluyendo el uso de expresiones regulares para limpiar datos.

4. **Interacción con APIs REST:**  
   Aprendiste a realizar peticiones HTTP (`GET`, `POST`) a APIs, a manejar respuestas en formato JSON y a integrar estos datos en DataFrames para su análisis.

5. **Ejercicios prácticos y automatización:**  
   Realizaste ejercicios para extraer títulos, precios, calificaciones y enlaces de libros, así como para guardar y analizar la información obtenida, aplicando todo lo aprendido en casos reales.

## 🚀 Para seguir aprendiendo :

---

- 📚 Vuelve a revisar este notebook y trata resolver por tu cuenta el proyecto nuevamente
- 💬 Recuerda que en Discord puedes dejar todos tus comentarios y dudas sobre el contenido del sprint en [Sprint 8](https://discord.com/channels/1081207584104656986/1270074133648113694).
    - 📝 Si tienes preguntas sobre tu proyecto, usa el canal `#project` para recibir ayuda y compartir ideas.
    - 🤝 Aprovecha el espacio de `CoLearning` para aclarar tus dudas junto con otros estudiantes e instructores: [Co-Learning](https://discord.com/channels/1081207584104656986/1197953851391746119).
- 📅 ¿Necesitas ayuda personalizada? Puedes agendar una sesión `1:1` conmigo aquí: [1:1 Roman Castillo](https://scheduler.zoom.us/roman-castillo/1-1-roman-castillo).

- Por último hazme paro y responde la encuesta al final de la sesión, me sirve para poder ayudarte mejor 

¡Sigue practicando y no dudes en pedir apoyo cuando lo necesites! 💪✨